pub const ERROR_CODE_OUT_OF_MEMORY: u32 = 0x1;
pub const ERROR_CODE_UNARY_OPERATOR_PARAM_TYPE: u32 = 0x12;
pub const ERROR_CODE_BINARY_OPERATOR_PARAM_TYPE: u32 = 0x13;
pub const ERROR_CODE_FUNCTION_APPLICATION_NOT_CALLABLE_TYPE: u32 = 0x16;
pub const ERROR_CODE_IF_STATEMENT_CONDITION_TYPE: u32 = 0x17;
